name: iozone # you probably want to 'snapcraft register <name>'
version: '471' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    iozone:
        command: bin/iozone

parts:
    benchmark:
        plugin: make
        source: src/iozone3_471.tar
        source-type: tar
        make-parameters: 
            - linux-AMD64
        #source: src/iozone3_471/
# TODO: figure out how to extract tar and then run make from a specific directory
#
